[package]
name = "installer_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.2"
egui = "0.18.1"
eframe = "0.18.0"
reqwest = {version = "0.11.10", features = ["blocking"]}